site_name: Pyneal Docs

# Directory where the raw content (i.e. markdown files) lives
docs_dir: content

# Subdirectories in the docs_dir where css tweaks live
# extra_css:
#     - css/extra.css

# Directory where you want the built site to turn up in
site_dir: docs

# Link the markdown files to a given page name
pages:
    - Introduction: index.md        # Note: first one HAS to be named index.md
    - Getting Started:
        - Installation: installation.md
        - Setup: setup.md
    - Troubleshooting: troubleshooting.md

# Specify the path to a custom theme. NOTE: 'name' has to be an already installed theme, tho
theme:
    name: material
    # custom_dir: theme/mkdocs-material/material

extra_css:
  - 'stylesheets/extra.css'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/jeffmacinnes/pyneal'

markdown_extensions:
  - toc:
      permalink: true
